---
title: "Lab 01 - Hello R!"
date: "2018-01-18 (updated `r Sys.Date()` by TL)"
author: "Mine Cetinkaya-Rundel and colleagues"
output: 
  html_document: 
    self_contained: no
  tufte::tufte_html:
    tufte_variant: "envisioned"
    highlight: pygments
    css: lab.css
    link-citations: yes
    self_contained: FALSE
---

```{r include=FALSE}
library(tidyverse)
library(datasauRus)
options(
  htmltools.dir.version = FALSE, # for blogdown
  show.signif.stars = FALSE     # for regression output
  )
```



```{r}
#library(tidyverse)
#library(datasauRus)
?datasaurus_dozen
colnames(datasaurus_dozen)
```
There are 1846 rows and 3 columns from the help file
The variable names are "dataset", "x", and "y"


```{r}
datasaurus_dozen %>%
  count(dataset) %>%
  print(13)
```



```{r fig.fullwidth=TRUE}
dino_data = datasaurus_dozen %>%
  filter(dataset == "dino")

ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```
```{r}
cor(dino_data$x,dino_data$y)

```
The correlation coefficient is -0.06447185.



```{r}
dino_data %>%
  summarize(r = cor(x, y))
```





```{r all-viz, eval=FALSE, fig.fullwidth=TRUE}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")
```


```{r all-r, eval=FALSE}
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y)) %>%
  print(13)
```

